default_stages: [pre-commit, pre-push]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: sort-simple-yaml
      - id: check-added-large-files
        exclude: ^uv\.lock$
      - id: check-toml
      - id: check-merge-conflict
      - id: check-yaml
        args:
          - --unsafe
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.10.3
    hooks:
      - id: uv-lock

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.1
    hooks:
      - id: ruff-check
        args: [--select, I, --fix]
      - id: ruff-format
  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.25
    hooks:
      - id: validate-pyproject

  # - repo: https://github.com/executablebooks/mdformat
  #   rev: 0.7.22
  #   hooks:
  #     - id: mdformat
  #       additional_dependencies:
  #         - mdformat-mkdocs==4.0.0
  #         - mdformat-footnote==0.1.1

  # - repo: https://github.com/igorshubovych/markdownlint-cli
  #   rev: v0.45.0
  #   hooks:
  #     - id: markdownlint-fix

  - repo: https://github.com/crate-ci/typos
    rev: v1
    hooks:
      - id: typos

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1
    hooks:
      - id: shellcheck
  - repo: https://github.com/rbubley/mirrors-prettier
    rev: v3.8.1
    hooks:
      - id: prettier
        # exclude: |
        #   (?x)^(
        #       antai-fullstack/frontend/src/client/.*|
        #       antai-fullstack/backend/app/email-templates/.*
        #   )$
  # - repo: https://github.com/igorshubovych/markdownlint-cli
  #   rev: v0.45.0
  #   hooks:
  #     - id: markdownlint
  #       args: ["--fix"]

  # zizmor detects security vulnerabilities in GitHub Actions workflows.
  # Additional configuration for the tool is found in `.github/zizmor.yml`
  - repo: https://github.com/woodruffw/zizmor-pre-commit
    rev: v1.22.0
    # don't update this until https://github.com/zizmorcore/zizmor-pre-commit/issues/24 is resolved
    # rev: v1.17.0
    hooks:
      - id: zizmor

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.36.2
    hooks:
      - id: check-github-workflows

  # setup uv to run type checking
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.10.3
    hooks:
      - id: uv-sync
        args: [--all-packages]
        stages: [] # make this hook runs in all stages
  # run type check with ty
  # - repo: local
  #   hooks:
  #     - id: ty-check
  #       name: ty-check
  #       language: python
  #       entry: ty check
  #       pass_filenames: false
  #       args: [--python=.venv/]
  #       additional_dependencies: [ty]

  - repo: https://github.com/facebook/pyrefly-pre-commit
    rev: 0.52.0 # Note: this is the version of the pre-commit hook, NOT the pyrefly version used for type checking
    hooks:
      - id: pyrefly-check
        name: Pyrefly (type checking)
        entry: uv run -m pyrefly check
        pass_filenames: false # Recommended to do full repo checks. However, you can change this to `true` to only check changed files
        # pass_filenames: true
        language: system # Use system-installed pyrefly
